apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: sample
spec:
  selectAllByDefault: true
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "350Mi"
    limits:
      cpu: "500m"
      memory: "850Mi"
  extraArgs:
    memory.allowedPercent: "40"
  remoteWrite:
  - url: "http://vmsingle-example-vmsingle-pvc.default.svc:8429/api/v1/write"
